name: Deploy

on:
  workflow_dispatch:
    inputs:
      check:
        required: true
        description: dunno
        type: boolean
      check2:
        required: true
        description: dunno
        type: boolean

jobs:
  deploy:
    uses: ./.github/workflows/conditions-test.yml
    with:
      check: ${{ inputs.check }}
      check2: ${{ inputs.check2 }}
    secrets: inherit
