name: Deploy

on:
  workflow_dispatch:
    inputs:
      run-test:
        required: true
        description: dunno
        type: boolean
      skip-test:
        required: true
        description: dunno
        type: boolean

jobs:
  deploy:
    uses: ./.github/workflows/conditions-test.yml
    with:
      run-test: ${{ inputs.run-test }}
      skip-test: ${{ inputs.skip-test }}
    secrets: inherit
  print:
    uses: ./.github/workflows/empty-dispatch-call.yml
