name: Schedule export jobs
on:
  schedule:
    - cron: "40 16 * * *"
    - cron: "45 16 * * *"
jobs:
  one:
    if: github.event.schedule == "40 16 * * *"
    uses: ./.github/workflows/dispatch.yml
    with:
      env: one
  two:
    if: github.event.schedule == "45 16 * * *"
    uses: ./.github/workflows/dispatch.yml
    with:
      env: two
