name: Schedule export jobs
on:
  schedule:
    - cron: '10 17 * * *'
    - cron: '25 17 * * *'
jobs:
  one:
    if: github.event.schedule == '10 17 * * *'
    uses: ./.github/workflows/dispatch.yml
    with:
      env: one
  two:
    if: github.event.schedule == '25 17 * * *'
    uses: ./.github/workflows/dispatch.yml
    with:
      env: two
