name: Schedule export jobs
on:
  schedule:
    - cron: '50 16 * * *'
    - cron: '55 16 * * *'
jobs:
  one:
    if: github.event.schedule == '50 16 * * *'
    uses: ./.github/workflows/dispatch.yml
    with:
      env: one
  two:
    if: github.event.schedule == '55 16 * * *'
    uses: ./.github/workflows/dispatch.yml
    with:
      env: two
