name: Test set result

on:
  workflow_dispatch:

jobs:
  one:
    if: inputs.run-step
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "run step"
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "should be always run"
